### ISSUE TITLE
Colors not displaying 

### ISSUE THREAD

**Issue by zjrubin** [trapd00r/LS_COLORS#128]
I am using the Windows Subsystem for Linux (WSL). I followed the setup instructions.

Here is my LS_COLORS:

![image](https://user-images.githubusercontent.com/46578381/56857880-87e0f080-6940-11e9-8f50-08c16407fa83.png)

But the correct colors do not show up for the file extension when I am viewing that are available where Windows is mounted:

![image](https://user-images.githubusercontent.com/46578381/56857911-c8406e80-6940-11e9-8d01-a0f8eca43677.png)

The colors are displaying fine as long as I am not in the /mnt folder or any of its subdirectories:
![image](https://user-images.githubusercontent.com/46578381/56858073-a6e08200-6942-11e9-8f97-bc8efdf9c025.png)

Any ideas what could be going wrong?

Here is the relevant portion of my .bashrc:

![image](https://user-images.githubusercontent.com/46578381/56857977-68969300-6941-11e9-92d8-a4c1c6aae074.png)

UPDATE: I think the issue is with the files being executable:
![image](https://user-images.githubusercontent.com/46578381/56858272-4e5eb400-6945-11e9-94d5-9bd514d5c2af.png)

Could someone please explain what is going on here?

Thanks!

**Comment by mattdkerr** [comment]
Try updating your distribution/WSL. What version of Windows are you on? I can't repro this with Ubuntu 18 LTS on 1903.

**Comment by rpdelaney** [comment]
This sure looks distribution specific. I for one use linux and cannot support WSL. It would be useful to know if _any_ dircolors configuration can be made to work.

**Comment by rpdelaney** [comment]
I'm closing this pending evidence that this is a problem with LS_COLORS. Feel free to use this thread to discuss troubleshooting using it on WSL though.
