### ISSUE TITLE
Colours to the permissions-part of ls command not work out of the box.

### ISSUE THREAD

**Issue by cofirazak** [trapd00r/LS_COLORS#137]
In the README.md there is this screenshot:

![Screenshot 2019-12-23 at 11 28 02](https://user-images.githubusercontent.com/2613578/71347084-8a9cef80-257a-11ea-855e-a05d069429f4.png)

From the readme it's not clear how can you apply colours to the permissions-part of ls command. 

Could you clarify how you did it?

**Comment by rpdelaney** [comment]
Japh wrote his own ls replacement that does that. We probably need new screenshots anyway since they haven't been updated in forever. I'll treat this as an issue to get new ones.

**Comment by cofirazak** [comment]
It would be great if Japh would share his own replacement in a gist for example.
Then you could just add a few words and a link to the gist below this screenshot in the readme.
By the way, thank you for reply.

**Comment by rpdelaney** [comment]
@cofirazak His ls replacement is linked from the readme. You may also like [exa](https://the.exa.website/) -- I have been using it for awhile.
