### ISSUE TITLE
[Question] Do I need zsh integeration

### ISSUE THREAD

**Issue by alivefromupstairs** [trapd00r/LS_COLORS#142]
I have a heavily modified version of `LS_COLORS` from this repo and I have `eval "$(dircolors $HOME/.config/LS_COLORS)"` in `~/.profile` to ensure it `LS_COLORS` gets generated once. problem with this is that whenever I make changes, I have to logout for them to take effect or eval dircolors in `.zshrc` (which would defeat the purpose). 

What does this zplugin plugin do exactly? does it load LS_COLORS from this repo, or can take a modified one? does it update whenever this repo updates or whenever LS_COLORS gets updated?
```
zplugin ice atclone"dircolors -b LS_COLORS > c.zsh" atpull'%atclone' pick"c.zsh"
zplugin load trapd00r/LS_COLORS
```

**Comment by rpdelaney** [comment]
See #136. We can't support zsh plugin managers here. Sorry :(

**Comment by alivefromupstairs** [comment]
@rpdelaney This is not about that at all. in fact, I am using the same zsh plugin manager as the README. the question is about what the plugin actually does. could you please re-read my issue or ask for clarification?

**Comment by rpdelaney** [comment]
Take a look at #136 for rationale on why I'm disinclined to support the docs even as they exist now. You're not wrong to expect a different response than what you're getting and I'm sorry. In that issue we are working on a revision to the README that won't give these wrong impressions.
