### ISSUE TITLE
Just a Qustion(sorry): Where can I find information about two-letter acronyms in the LS_COLORS?

### ISSUE THREAD

**Issue by asgharam** [trapd00r/LS_COLORS#175]
Sorry I couldn't ask this question elsewhere so I had to ask here. I have a question about words like "bd" "ca" "cd" etc. I couldn't find any information in dircolors manual or dircolor database(`dircolors -p`) about them. can you help me?

**Comment by trapd00r** [comment]
https://github.com/coreutils/coreutils/blob/master/src/dircolors.c#L62 

Line 62 to 77. :)

**Comment by asgharam** [comment]
Thanks. And how is that not in the manual?! Now I have to read the source code to find out how to use a program? I know it has nothing to do with you but I can't wrap my head around it :/

**Comment by trapd00r** [comment]
You can ask on the coreutils mailing list.
