### ISSUE TITLE
Feature Request: Add a script that prints out all colors and associated files

### ISSUE THREAD

**Issue by trallnag** [trapd00r/LS_COLORS#179]
It would be nice to have a script (either in the repository itself or documented in the wiki) that prints out all colors and associated files / file types / extensions.

**Comment by rpdelaney** [comment]
@trallnag Since you closed the issue, do you not actually need this?

**Comment by trapd00r** [comment]
https://github.com/trapd00r/LS_COLORS/blob/japh/bin/whatdoesitlooklike
