### ISSUE TITLE
script files are hard to reproduce in systems with different locales

### ISSUE THREAD

**Issue by anakimluke** [trapd00r/LS_COLORS#194]
I noticed the .sh and .csh files provided in the repo are different from what I get from trying to use the makefile myself. After some digging, I found it's because github action's locales are different from my system's, which cause `sort` to show different output.

So I suggest adding something like `export LC_ALL=C` to the makefile to force `sort` to use the same locale regardless of which system it is run.

**Comment by rpdelaney** [comment]
Good idea. I'll look at this when I get a chance. In the mean time, PRs are very welcome :)
