### ISSUE TITLE
tcsh ls_color doesn't work when doing `ls`. `echo $LS_COLORS` prints "echo: No match."

### ISSUE THREAD

**Issue by Anthonyive** [trapd00r/LS_COLORS#199]
The `ls_colors.csh` script was working for me when tcsh version is 6.18.01

```tcsh
> $SHELL --version
tcsh 6.18.01 (Astron) 2012-02-14 (x86_64-unknown-linux) options wide,nls,lf,dl,al,kan,sm,color,filec
```

but now when I'm on another host where the version is 6.21.00, the `ls_colors.csh` script stops working

```tcsh
> $SHELL --version
tcsh 6.21.00 (Astron) 2019-05-08 (x86_64-unknown-linux) options wide,nls,dl,al,kan,sm,rh,nd,color,filec
```

<img width="448" alt="Screenshot 2023-06-23 084414" src="https://github.com/trapd00r/LS_COLORS/assets/8257285/dfbfd743-87fb-4fcb-ae2e-96afb7d8eb6a">

What I did was just source this file in the cshrc. I have `dircolors` on both hosts

**Comment by rpdelaney** [comment]
This sounds like a problem with tcsh. Please report your problem to the community support channels for tcsh.
