### ISSUE TITLE
Make SETUID/SETGID easier to distinguish from normal files

### ISSUE THREAD

**Issue by ThiefMaster** [trapd00r/LS_COLORS#21]
Right now SETGID has a background color (albeit hard to notice on black bg) while SETUID doesn't. In any case, SETUID should be *much* more obvious than anything else.

Yellow/red background like the default `DIR_COLORS` use might not be too bad. Maybe darker but an "alarmy" color would be a good idea.

**Comment by rpdelaney** [comment]
Can you point out some resources for understanding the significant differences between `SETGID` and `SETUID`?

**Comment by ThiefMaster** [comment]
- SETGID on an executable changes the group it's running as..
- SETUID changes the user (in most cases to root)

Usually SETGID is used e.g. to provide a program access to a specific file/folder such as /var/log/wtmp (which is writable by a certain group), while SETUID is used for programs that need full root permissions (anything that uses raw sockets for example, or tools that need to update /etc/passwd or /etc/shadow).

**Comment by rpdelaney** [comment]
That does seem like something worth shouting about. Take a look at this commit and let me know if it's loud enough for you. Also @trapd00r ? 

0ea48a2ce282e46045ebcb30174ec17199b8dbc0

**Comment by trapd00r** [comment]
Seens reasonable. :-)

**Comment by ThiefMaster** [comment]
Different colors would be nice (setuid is more dangerous than setgit)

My suggestion would be this:
```
SETGID                48;5;3;38;5;0
SETUID                48;5;1;38;5;253
```

**Comment by rpdelaney** [comment]
How about a compromise? I find the bold-on-yellow to be the most eye-catching without hurting my eyes.

```
SETGID                48;5;3;38;5;0
SETUID                38;5;220;1;3;100;1
```

**Comment by rpdelaney** [comment]
@ThiefMaster your thoughts?

**Comment by ThiefMaster** [comment]
Probably a matter of taste - I like setuid to be quite obvious. But I guess your suggestion is a good compromise (and on my own systems I use a slighly modified version anyway)

**Comment by rpdelaney** [comment]
Ok, I'll merge this in. Thanks
