### ISSUE TITLE
Add support for light background

### ISSUE THREAD

**Issue by glensc** [trapd00r/LS_COLORS#217]
Seems this is designed for dark background, as with light background the filenames are quite hard to read.

<img width="605" alt="image" src="https://github.com/trapd00r/LS_COLORS/assets/199095/899b5c5f-b679-40d6-b294-7105a3b888f5">

**Comment by rpdelaney** [comment]
That would require maintaining two lists and rebuilding a color scheme from scratch. Maintainers don't use light theme, so I don't see this happening before a major restructuring, e.g. a migration to [`vivid`](https://github.com/sharkdp/vivid)
