### ISSUE TITLE
buildsuite uses `grep -P`

### ISSUE THREAD

**Issue by hurufu** [trapd00r/LS_COLORS#39]
`grep -P` is an experimental feature and is not available on some platforms, easy patch will be something like `perl -ne 'if (/^[\.\*]([A-z0-9]+)/) { print $1; }'`

**Comment by rpdelaney** [comment]
You're right. Looking at this again, it should be doable with another sed expression - no need for `grep -P` or perl.

**Comment by rpdelaney** [comment]
@hurufu 
Would you mind having a look at #43 before I merge it in?

**Comment by rpdelaney** [comment]
Fixed in #43
