### ISSUE TITLE
README screenshot image is a broken link

### ISSUE THREAD

**Issue by drewnoakes** [trapd00r/LS_COLORS#51]
The project's front page (readme) looks like this to me now:

> ![image](https://cloud.githubusercontent.com/assets/350947/13030854/b7cb1be2-d2b0-11e5-87f1-866944755ce3.png)

Here is the [direct link](https://camo.githubusercontent.com/e235af63c2be86cf4e4167b7f098e28192b63488/687474703a2f2f646576656c2e6a6170682e73652f4c535f434f4c4f52532f4c535f434f4c4f52532e706e67). I get a 404.

**Comment by rpdelaney** [comment]
Looks okay to me. I guess this was fixed somewhere along the line.

**Comment by drewnoakes** [comment]
Yep. Looks fine now.
