### ISSUE TITLE
Install LS_COLORS on ksh on putty

### ISSUE THREAD

**Issue by fabeit** [trapd00r/LS_COLORS#63]
Hello, thanks for the nice work!
I can't make LS_COLORS work on a ksh terminal. I have downloaded LS_COLORS and added the eval command to my .kshrc but nothing happens. 

Could you help?
Thanks!

**Comment by trapd00r** [comment]
I tried a few things, but I have no knowledge of ksh, sorry. Works in bash?

**Comment by rpdelaney** [comment]
Does ksh even support dircolors?

**Comment by fabeit** [comment]
I "think" it's working, I set an aliases with ls color=auto, and I think it's reading the ls_colors.

**Comment by rpdelaney** [comment]
Not a problem with LS_COLORS. Please seek support from ksh mailing lists or such.
