### ISSUE TITLE
error: invalid character '=' in LSCOLORS env var

### ISSUE THREAD

**Issue by samangh** [trapd00r/LS_COLORS#64]
Trying to use LS_COLORS in OS X (Note, it's LSCOLORS in OS X, not LS_COLORS).

```
eval $(dircolors -b ~/.LS_COLORS/LS_COLORS)
export LSCOLORS=$LS_COLORS
```

But, I get:

```
$ ls
error: invalid character '=' in LSCOLORS env var
warn: LSCOLORS should use characters a-h instead of 0-9 (see the manual page)
error: invalid character '8' in LSCOLORS env var
error: invalid character ';' in LSCOLORS env var
error: invalid character ';' in LSCOLORS env var
error: invalid character '8' in LSCOLORS env var
error: invalid character ':' in LSCOLORS env var
error: invalid character '=' in LSCOLORS env var
error: invalid character '8' in LSCOLORS env var
error: invalid character ';' in LSCOLORS env var
error: invalid character ';' in LSCOLORS env var
error: invalid character ':' in LSCOLORS env var
```

Any ideas?

**Comment by samangh** [comment]
Can see result of `echo $LS_COLORS` in [this gist](https://gist.githubusercontent.com/samangh/dc283a0b3e66f556ffcd4e49ab7c5e23/raw/1c4bbdfb3b9fb838bbfb5ff88ba8c3b28adbcb04/LS_COLORS.var).

**Comment by rpdelaney** [comment]
Weird. Works for me in OSX using `LS_COLORS` as normal. What's your `$SHELL`?

**Comment by samangh** [comment]
Found the problem, it's with `ls`. I switched from the OS X `ls` to the latest version of GNU `ls` (v8.25), and LS_COLORS now works fine.

I wonder whether there is a difference between how BSD and GNU variants interpret `$LS_COLORS`, or if its just that the `ls` shipped in OS X is too old.
