### ISSUE TITLE
A minor misnaming of an extension

### ISSUE THREAD

**Issue by Ghostotw** [trapd00r/LS_COLORS#70]
Lines 928-929 show .scm as a GIMP project file. A GIMP project file is actually .xcf; .scm is the extension for the "scheme" scripting language which is commonly used to write GIMP filters. I don't know that .scm is exclusive to GIMP, though.

If you are interested, here are a few more GIMP extensions;
.gpl - palette
.pat - pattern
.gtp - tool preset
.ggr - gradient
.gdyn - brush dynamic

**Comment by rpdelaney** [comment]
That's a drag. Is this still an issue? Sorry for the late replies but I don't seem to be getting emails when these issues are created.

**Comment by Ghostotw** [comment]
I honestly don't know if it's still an issue. I haven't used that OS or this program in more than a year. It didn't cause any problems, was just a trivial inaccuracy.
