### ISSUE TITLE
add new extension

### ISSUE THREAD

**Issue by xtmgah** [trapd00r/LS_COLORS#76]
Can you set different color for these extension? i don't know how to change it in my hand:

*.bam 
*.bai
*.vcf
*.bed
*.R
*.RData

thanks.

**Comment by rpdelaney** [comment]
Please describe the file types and I'll see if I can get them sorted in eventually.

**Comment by Gorzen** [comment]
Maybe but I'm pretty sure it's not the vcf he meant
`.bam`, `.bai` and `.vcf` are all stuff about genomics (DNA, ...)
`.bam` is the actual data (compressed binary version of a `SAM` file which represent aligned sequences (ATCG...))
`.bai` is an index for the `.bam` file (to index sequence positions)
`.vcf` is for Variant Call Format, basically says where and what variants you have between two genomes

The other ones I don't really know much about them but also data stuff

**Comment by rpdelaney** [comment]
PRs welcome :)
