### ISSUE TITLE
Differentiation for symlinks

### ISSUE THREAD

**Issue by gibfahn** [trapd00r/LS_COLORS#83]
AFAICT symlinks are coloured according to the extension of the link:

https://github.com/trapd00r/LS_COLORS/blob/73965bdb95f2637f5f7271571ea2595d542cb66f/LS_COLORS#L44

This makes it difficult to tell from a simple `ls` whether a file is a symlink, whereas it's a different color in standard color schemes.

What would be ideal would be a format that preserved the color of the extension while adding something else (e.g. underline, inverted colors, or italics, preferably not italics as it doesn't work on many terminals). I understand that may be difficult as underline is already used for `.docm` `.pptxm` `.pptsm` `.xlsxm` `.xltm` and `LS_COLORS`, but it'd make a big difference (at least for me).

#### `LS_COLORS` output:

<img width="413" alt="image" src="https://user-images.githubusercontent.com/15943089/35896137-cacac348-0bf5-11e8-943e-4c901ce7caed.png">

#### `gls` and `ls` output on macOS:

![image](https://user-images.githubusercontent.com/15943089/35896168-f5b1c5de-0bf5-11e8-840a-e64a99d14abb.png)

Orphan links are already highlighted, which is great.

https://github.com/trapd00r/LS_COLORS/blob/73965bdb95f2637f5f7271571ea2595d542cb66f/LS_COLORS#L50

Sorry if this has come up before, couldn't find an issue that mentioned it.

**Comment by rpdelaney** [comment]
I haven't looked at this closely but I'm not sure dircolors supports it.

I'm shocked -- shocked! -- to discover we're using underline for MS Office documents. That makes little sense to me. My terminals or fonts don't support it, I guess.

**Comment by gibfahn** [comment]
Yeah, looks like you're right, adding support for this would require actually modifying the source for `ls`, which is not something I have much experience with.

https://github.com/coreutils/coreutils/blob/e5dae2c6b0bcd0e4ac6e5b212688d223e2e62f79/src/ls.c#L350-L362

Thanks for the response though!
