### ISSUE TITLE
What do the color definitions represent in hex or rgba?

### ISSUE THREAD

**Issue by bearcatsandor** [trapd00r/LS_COLORS#87]
This is less of a bug and more of a question, but what do the color definitions in LSCOLORS represent? If i were to take a color from that file, let's say 
   .wv                   38;5;136;1

It's obviously not rgba.  How do i translate that to hex or rgba? Googling for it doesn't give me anything to go on, 

I'm trying to convert a vim theme to my lscolors file.

Thank you

**Comment by rpdelaney** [comment]
I believe this is explained in the dircolors manpage: `man dircolors`
