### ISSUE TITLE
Last updated date is 2016

### ISSUE THREAD

**Issue by rpdelaney** [trapd00r/LS_COLORS#99]
The version hasn't been updated in forever either. Fix that and then figure out some way to automate it since I am not going to remember

**Comment by maximbaz** [comment]
Do you really need to keep version in the file though? Maybe just drop it completely 🙂 If someone cared about it, you would have seen a bug about it by now.

**Comment by rpdelaney** [comment]
Yeah I dunno. Github recently added a feature that might be able to handle this in an automated fashion, but it's a very low priority regardless. Mainly I think it looks a bit unprofessional, but that's all. 

The one thing that I do think is significant is the copyright date. I've just done that in #103. Maybe I can handle that manually if I only have to do it once a year, but as we've seen from past experience perhaps I shouldn't be so optimistic.

**Comment by maximbaz** [comment]
> Github recently added a feature that might be able to handle this in an automated fashion

Can you share a link? 🙂
